In [1]:


import math
import cv2 as cv
import matplotlib.pyplot as plt 
#get_ipython().run_line_magic('matplotlib', 'inline')
import numpy as np 
import os
os.path
os.chdir('E:\pycharmfile\opencv')



In [2]:




def mkG(img,n):
   # 制造高斯空间 
    Gspace=[]
    g=img.copy()
    Gspace.append(g)
    for i in range(n):
        g = cv.pyrDown(g)
        Gspace.append(g)
    return Gspace



In [3]:


def mkDOGandAngelspace(img,segma,n):
    #制造dog空间
    DOGspace=[]
    Gspace=[img]
    old_g=img.copy()
    for i in range(n):
        g=img.copy()
        m = int(2*segma*(i+1)+1)
        g = cv.GaussianBlur(img,(m,1),0)
        g = cv.GaussianBlur(g,(1,m),0)
        Gspace.append(g)
        DOGspace.append( cv.absdiff(g,old_g) )
        old_g = g
        if i==3:
            
    return DOGspace,Gspace

    



In [4]:


def FindKeypoint(space,idx):
    #寻找关键点
    Keypoint = []
    shape=[len(space),len(space[0]),len(space[0][0])]
    for i in range(1,shape[0]-1):
        for j in range(1,shape[1]-1):
            for k in range(1,shape[2]-1):
                if ifkeypoint(i,j,k,space,shape) and ifedge(i,j,k,space):
                    Keypoint.append([i,j*idx,k*idx])
    return Keypoint



In [5]:


def ifkeypoint(i,j,k,space,shape):

    dx=[0,1,-1]
    dy=[0,1,-1]
    dz=[0,1,-1]
    flag=0
    dnow=space[i][j][k]
    for ix in range(3):
        for iy in range(3):
            for iz in range(3):
                if flag==0 :
                    flag=1
                    continue
                if space[i+dx[ix]][j+dy[iy]][k+dz[iz]] >= dnow :
                    return False
    return True



In [1]:
def ifedge(i,j,k,space):
    dx=space[i][j+1][k]+space[i][j+1][k-1]+space[i][j+1][k+1]
    -(space[i][j-1][k]+space[i][j-1][k-1]+space[i][j-1][k+1])
    dx=abs(dx)
    dy=space[i][j+1][k+1]+space[i][j][k+1]+space[i][j-1][k+1]
    -(space[i][j+1][k-1]+space[i][j][k-1]+space[i][j-1][k-1])
    dy=abs(dy)
    if dy==0 or dx==0: return false
    t=1.0*dx/dy
    if t<10 and t>0.1: 
        return True
    else :
        return False
    
    

In [6]:



def showpic(img):
    cv.imshow('image',img)
    cv.waitKey(0)
    cv.destroyAllWindows()



In [10]:
def angel(Keypoint,Aspace):
    i,j,k=Keypoint
    Aspace=Aspace[j-4:j+5][k-4:k+5]
    sobelx=cv.Sobel(Aspace,cv.CV_64F,1,0,ksize=3)
    sobely=cv.Sobel(Aspace,cv.CV_64F,0,1,ksize=3)
    a=sobelx*sobelx
    b=sobely*sobely
    m=a+b
    m=m**0.5
    m=cv.GaussianBlur(m,(9,9),0)
    outm=m[j,k]
    c=a+b
    outa=np.zeros(8)
    for idxj in range(9):
        for idxk in range(9):
            dx=sobelx[idxj,idxk]
            dy=sobely[idxj,idxk]
            nowang=0
            if dx==0 and dy!=0:
                nowang=0.5*np.pi if dy>0 else 1.5*np.pi 
            else if dx!=0 and dy==0:
                nowang=1*np.pi if dx<0 else 0
            else :
                nowang=np.arcsin(dy/dx)
                if dx<0: nowang+=np.pi 
            nowang=(nowang+2*np.pi)%2*np.pi 
            angidx=int(nowang/0.25*np.pi)
            outa[angidx]+=1
    outangle=outa.argmax()
    return outm,outa

    

SyntaxError: invalid syntax (<ipython-input-10-63105e6ea365>, line 1)

In [7]:


def showpoint(Keypoint,img):
    for point in Keypoint:
        cv.circle(img,(point[1],point[2]), 3, (0,0,255), 1)



In [8]:


def text():
    img=cv.imread('cat2.jpg')
    img = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    space = mkG(img,5)
    G_DOGspace = []
    g=img.copy()
    idx=1
    for pic in space:
        DOGspace,Aspace=mkDOGandAnglespace(pic,20,5)
        #G_DOGspace.append(DOGspace)
        Keypoint = FindKeypoint(DOGspace,idx)
        angel(Keypoint,Aspace)
        showpoint(Keypoint,g)
        idx*=2
    cv.imwrite("2'.jpg",g )



In [23]:
text()



In [24]:
b=SiftFeature()
print(b.Keypoint)
c=SiftFeature([2,3,4,5,1])
c.Keypoint

[]


[2, 3, 4, 5, 1]

In [33]:
img=cv.imread('cat.jpg')
img=cv.cvtColor(img,cv.COLOR_BGR2GRAY)

sobelx=cv.Sobel(img,cv.CV_64F,1,0,ksize=3)
sobelx.shape

(1440, 1080)

In [66]:
a=np.zeros(8)
a[6]+=1
a.argmax()

6

In [58]:
a=np.arcsin(b/c)
a=a/np.pi
a

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [57]:
b=np.ones((3,3))
c=np.zeros((3,3))

In [48]:
a =1 if 2<3 else 5
a

1

In [73]:
c=a[1:3,1:3]
c

array([[0., 0.],
       [0., 0.]])

In [71]:
a=np.zeros((5,5))

In [45]:
a=a**0.5
a

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [46]:
a=2/0
a

ZeroDivisionError: division by zero

In [2]:

def extract_features(image_paths):
    sift_det = cv2.xfeatures2d.SIFT_create()
    imgDes_list = []  # 所有图像的所有sift descriptor的列表
    for i, image_path in enumerate(image_paths):
        img = cv2.imread(image_path)
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        kp, img_des = sift_det.detectAndCompute(gray, None) 
# 以第一幅图像为例，kp是这幅图像的所有keypoints。img_des是这幅图像的keypoint descriptor的列表，
#它的shape为(3765, 128)。即第一幅图像中提取到了3765个关键点，每个关键点对应一个描述符，而一个描述#符是一个128维的向量。
        imgDes_list.append(img_des)
    return imgDes_list

In [8]:
        sift_det = cv.xfeatures2d.SIFT_create()
        img = cv.imread('img1.ppm')
        gray = cv.cvtColor(img, cv.COLOR_RGB2GRAY)
        kp, img_des = sift_det.detectAndCompute(gray, None) 

In [10]:
img_des.shape

(3376, 128)